# theme.toml template for a Hugo theme
# See https://github.com/gohugoiox/hugoThemes#themetoml for an example

name = "Hextra"
license = "MIT"
licenselink = "https://gitlab.com/tffhrtp/tffhrtp-website/docs-website/tffhrtp-docs-ui/-/blob/main/LICENSE"
description = "Modern, responsive, batteries-included Hugo theme for creating beautiful static websites."
homepage = "https://gitlab.com/tffhrtp/tffhrtp-website/docs-website/tffhrtp-docs/"
demosite = "https://docs.fhrp.org"
tags = ["Modern", "Elegant", "Blog", "Documentation", "Responsive", "Clean", "Light", "Dark", "Minimal"]
features = ["Responsive", "Dark Mode", "Search", "Syntax Highlighting", "Multilingual", "Social", "Blog", "RSS", "Customization"]
min_version = "0.124.0"

[author]
  name = "TFFHRTP"
  homepage = "https://fhrp.org/"
